dataset: dataset/test
model_weights: weights/best-checkpoint-114epoch.bin 
output_dir: inference/original 
# model_weights: weights/best-checkpoint-fine-tune-aug.bin
# output_dir: inference/fine_tune_aug
model_weights: weights/best-checkpoint-fine-tune-no-aug.bin
output_dir: inference/fine_tune_no_aug
confidence_threshold: 0.9