### Dataset ###
train_dataset_path: dataset/example_mask
val_dataset_path: dataset/example_mask
test_dataset_path: dataset/example_mask

### Optimizer ###
n_trails: 10
n_epochs: 100
patience: 10
batch_size:
  min: 1
  max: 8
learning_rate:
  min: 0.00001
  max: 0.0001

### Model ###
model_name: mask_rcnn
model_dir: model/fine_tune

