### Dataset ###
train_dataset_path: dataset/train
val_dataset_path: dataset/val
test_dataset_path: dataset/test

### Optimizer ###
n_trails: 30
n_epochs: 5
patience: 10
batch_size:
  - 4
  - 8
  - 16
  - 32
learning_rate:
  min: 0.00001
  max: 0.001
freeze_weights:
  - True
  - False
data_augmentation: 
  - False
  - True

### Model ###
model_name: mask_rcnn
model_dir: model/fine_tune

### Neptune ###
neptune_workspace: francesco-campi
neptune_project: DKFZ-Organoid-Detection-example

