### Dataset ###
train_dataset_path: dataset/multiorg_split/train_B
val_dataset_path: dataset/multiorg_split/val_B

seed: 42
annotator: 1

### Optimizer ###
n_trials: 80
n_epochs: 50
patience: 10
batch_size:
  - 8
  - 16
  - 32
  - 64
learning_rate:
  min: 0.000005
  max: 0.005
data_augmentation: 
  - True
  - False
backbone:
  - 18
  - 34
  - 50
  - 101
trainable_layers:
  - 2
  - 3
  - 4
  - 5

### Model ###
model_name: faster_rcnn
model_dir: model/fine_tune_multiorg_B

### Neptune ###
neptune_workspace: francesco-campi
neptune_project: Multiorg-B


