### Dataset ###
train_dataset_path: dataset/train_multirater
val_dataset_path: dataset/val_multirater
test_dataset_path: dataset/test_multirater

seed: 42
annotator: 2

### Optimizer ###
n_trials: 80
n_epochs: 150
patience: 25
n_gpus: 1
batch_size:
  - 8
  - 16
  - 32
learning_rate:
  min: 0.000005
  max: 0.005
freeze_weights:
  - True
  - False
data_augmentation: 
  - True
  - False

### Model ###
model_name: mask_rcnn
model_dir: model/fine_tune_multirater_1

### Neptune ###
neptune_workspace: francesco-campi
neptune_project: DKFZ-Organoid-Detection-aug


