### Dataset ###
train_dataset_path: dataset/train
val_dataset_path: dataset/val
test_dataset_path: dataset/test
seed: 42

### Optimizer ###
n_trials: 80
n_epochs: 150
patience: 25
batch_size:
  - 8
  - 16
  - 32
  - 64
learning_rate:
  min: 0.000005
  max: 0.005
freeze_weights:
  - True
  - False
data_augmentation: 
  - True

### Model ###
model_name: mask_rcnn
model_dir: weights/fine_tune_aug

### Neptune ###
neptune_workspace: francesco-campi
neptune_project: DKFZ-Organoid-Detection-aug


