### Dataset ###
train_dataset_path: dataset/train
val_dataset_path: dataset/val
test_dataset_path: dataset/test
seed: 42

### Optimizer ###
n_trials: 40
n_epochs: 150
patience: 25
n_gpus: 1
batch_size:
  - 8
  - 16
  - 32
learning_rate:
  min: 0.00001
  max: 0.001
freeze_weights:
  - True
  - False
data_augmentation: 
  - False

### Model ###
model_name: mask_rcnn
model_dir: model/fine_tune_no_aug

### Neptune ###
neptune_workspace: francesco-campi
neptune_project: DKFZ-Organoid-Detection-no-aug


